<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>e-Way Bill</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        .container {
            width: 800px;
            margin: auto;
            padding: 20px;
            /* border: 1px solid #ddd; */
        }
        .header {
            text-align: center;
            font-size: 22px;
            font-weight: bold;
        }
        .section {
            margin-top: 15px;
            padding-bottom: 10px;
            border-bottom: 1px solid #000;
        }
        .row {
            display: flex;
            justify-content: space-between;
            font-size: 14px;
            /* padding: 4px; */
        }
        .column {
            width: 48%;
            padding: 4px;
        }
        .bold {
            font-weight: bold;
        }
        .qr-code {
            text-align: right;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        .table th, .table td {
            border-bottom: 1px solid #000;
            padding: 8px;
            text-align: left;
        }
        .table th {
            font-weight: bold;
        }
        .invoice-box table {
            width: 100%;
            border-collapse: collapse;
        }
        .invoice-box th, .invoice-box td {
            border: 1px solid #000;
            padding: 5px;
            text-align: left;
        }
        .invoice-header {
            border: 1px solid black;
            padding: 10px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            page-break-before: always;
            position: relative;
        }
        .company-details {
            text-align: center;
            flex: 1;
        }
        .company-details h2 {
            margin: 0;
            font-size: 14px;
            font-weight: bold;
        }
        .company-details p {
            margin: 2px 0;
        }
        .qr-code {
            width: 100px;
            height: 100px;
        }
        .logo {
            width: 100px;
            height: auto;
        }
        .invoice-info {
            border: 1px solid black;
            /* margin-top: 5px; */
            padding: 5px;
        }
        .invoice-info table {
            width: 100%;
            border-collapse: collapse;
        }
        .invoice-info td {
            /* border: 1px solid black; */
            padding: 5px;
        }
        .tiio{
            margin: 0;
    font-size: 10px;
    position: absolute;
    top: 3px;
    right: 4px;
    font-weight: 600;
        }
        .invoice-box {
            width: 100%;
            max-width: 800px;
            margin: auto;
            /* border: 1px solid #000;
            padding: 10px; */
        }
        .no-border {
            border: none !important;
        }
        .rno-border{
            border-right: none !important;
            border-top:none !important;
            border-bottom:none !important;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">e-Way Bill</div>

        <div class="section">
            <div class="row">
                <div class="column ">
                    <p style="margin: 2px;">Doc No : <b>Tax Invoice - MIS/INV24-25/592</b>
                    </p>
                    <p style="margin: 2px;">Date   : <b>10-Feb-25</b></p>
                </div>

                <div class="column qr-code"><img src="assets/images/qrc.png" alt="QR Code" width="80"></div>
            </div>




            <div class="row">
                <div class="column">IRN : <b>5fd3d74cc14cb42551821fbf6</b></div>
            </div>
            <div class="row">
                <div class="column">Ack No. : <b>152520706410832</b></div>
            </div>
            <div class="row">
                <div class="column">Ack Date : <b>10-Feb-25</b></div>
            </div>
        </div>

        <div class="section">
            <div class="bold" style="padding: 4px;">1.e-Way Bill Details</div>
            <div class="row">
                <div class="column">e-Way Bill No.: <b>571771268064</b></div>
                <div class="column">Mode: <b>1 - Road</b></div>
                <div class="column">Generated Date : <b>10-Feb-25 10:38 PM</b></div>
            </div>
            <div class="row">
                <div class="column">Generated By: <b>33BUPK1095F1ZC</b></div>
                <div class="column">Approx Distance: <b>487 KM</b></div>
                <div class="column">Valid Upto : <b>13-Feb-25 11:59 PM</b></div>
            </div>
            <div class="row">
                <div class="column">Supply Type : <b>Outward-Supply</b></div>
                <div class="column">Transaction Type : <b>Bill From - Dispatch From</b>
                </div>
                <div class="column"></div>
            </div>
        </div>

        <div class="section">
            <div class="bold" style="padding: 4px;">2.Address Details</div>
            <div class="row">
                <div class="column bold">From</div>
                <div class="column bold">To</div>
            </div>
            <div class="row">
                <div class="column">MERCURI INDUSTRIAL SOLUTIONS<br>GSTIN: 33BUPK1095F1ZC<br>Tamil Nadu</div>
                <div class="column">ASHTALAKSHMI PURIFIERS<br>GSTIN: 33AARFA5297N1ZQ<br>Tamil Nadu</div>
            </div>
            <div class="row">
                <div class="column bold">Dispatch From</div>
                <div class="column bold">Ship To</div>
            </div>
            <div class="row">
                <div class="column">TMTE METAL TECH PRIVATE LIMITED,
                    33AACCT6677P1ZM-No104 Pennalur Village Near
                    Rajalakshmi Health Centre, Sriperumbudur
                    </div>
                <div class="column">S.F NO: 1, SATHY MAIN ROAD, SARAVANAMPATTY
                    POST,, COIMBATORE - 641 035
                    Coimbatore Tamil Nadu 641035
                    </div>
            </div>
        </div>
    <div class="section">
        <div class="bold" style="padding: 4px;">3.Goods Details</div>
    </div>
        <div class="section" style="border-bottom: none;">

            <table class="table">
                <tr>
                    <th>HSN Code</th>
                    <th>Product Name & Desc</th>
                    <th>Quantity</th>
                    <th>Taxable Amt</th>
                    <th>Tax Rate (C+S)</th>
                </tr>
                <tr>
                    <td>94032010</td>
                    <td>Selective Pallet Racking System & Selective Pallet Racking System</td>
                    <td>22 NOS</td>
                    <td>4,53,200.00</td>
                    <td>9+9</td>
                </tr>
            </table>
        </div>

        <div class="section">
            <div class="row">
                <div class="column">Tot. Taxable Amt: <strong>4,53,200.00</strong></div>
                <div class="column">Other Amt : <strong></strong></div>

                <div class="column">Total Inv Amt: <strong>5,34,776.00</strong></div>
            </div>
            <div class="row">
                <div class="column">CGST Amt: <strong>40,788.00</strong></div>
                <div class="column">SGST Amt: <strong>40,788.00</strong></div>
                <div class="column"> <strong></strong></div>
            </div>
        </div>

        <div class="section">
            <div class="bold"  style="padding: 4px;">4.Transportation Details</div>
            <div class="row">
                <div class="column">Transporter ID: <strong>33AADCW7680E1Z8</strong></div>
                <div class="column">Doc No.: ________</div>
            </div>
            <div class="row">
                <div class="column">Name: <strong>WEHAUL LOGISTICS PRIVATED LIMITED</strong></div>
                <div class="column">Date: ________</div>
            </div>
        </div>

        <div class="section">
            <div class="bold"  style="padding: 4px;">5.Vehicle Details</div>
            <div class="row">
                <div class="column">Vehicle No.: <strong>TN24AE6518</strong></div>
                <div class="column">From: <strong>Chennai</strong></div>
                <div class="column">CEWB No.: ________</div>
            </div>
        </div>

        <div class="invoice-header">
            <img src="assets/images/qrc1.png" alt="QR Code" class="qr-code">
            <div class="company-details">
                <h2>MERCURI INDUSTRIAL SOLUTIONS</h2>
                <p>Wing 5 Flat 3D, Keyees Samyuktha,</p>
                <p>771/2B Church Road Vailan Nagar,</p>
                <p>Madhambakkam, Kanchipuram-600126</p>
                <p>Tel: (L) - (M) 9578598990</p>
                <p>E-Mail: kathir@mercuriis.com Website: www.mercuriis.com</p>
            </div>
            <div>
            <p class="tiio">(ORIGINAL FOR RECIPIENT)</p>
            <img src="/assets/images/logom.png" alt="Company Logo" class="logo">
            </div>
        </div>

        <div class="invoice-info">
            <table>
                <tr>
                    <td style="border:none;"><strong>IRN :</strong> 5fd347cc14eb4258</td>
                </tr>
                <tr>
                    <td style="border:none;"><strong>Ack No :</strong> 15252074610832</td>
                    <td style="border:none;"><strong>Ack Date :</strong> 10-2-2025</td>
                </tr>
            </table>
        </div>
        <div class="invoice-box">
            <table>
                <tr>
                    <td colspan="2" style="border-right: none;"><strong>GSTIN:</strong> 33BUXPKI095F1ZC</td>
                    <td class="header" colspan="2" style="border-left: none;">Tax Invoice</td>
                </tr>
                <tr>
                    <td colspan="2" style="width: 50%;">
                        <p><strong>Billing Address</strong></p>
                        <p>ASHTALAKSHMI PURIFIER
                            S.F NO: 1, SATHY MAIN ROAD, SARAVANAMPATTY POST,
                            COIMBATORE - 641 035</p>
                            <p><b>Mobile:</b> </p>
                            <p><strong>State:</strong> Tamil Nadu &nbsp;&nbsp; <strong>State Code:</strong> 33<br> </p>
                            <p><b>Pincode:</b> 641035</p>
                            <p><b>GSTIN:</b> 33AARFA5297N1ZQ</p>

                    </td>
                    <td colspan="2" style="width: 50%;">
                        <p><strong>Invoice No:</strong> MIS/INV24-25/592</p>
                        <p><strong>Invoice Date:</strong> 10-Feb-25</p>
                        <p><strong>Order No:</strong> 055 - REV</p>
                        <p><strong>Order Date:</strong> 10-Jan-25</p>
                        <p><strong>HSN/SAC Code:</strong> 94032010</p>
                        <p><strong>Eway Bill No:</strong> 577171268064</p>

                    </td>
                </tr>
            </table>

            <table>
                <tr>
                    <th>Sl No</th>
                    <th>Part No</th>
                    <th>Description of Goods</th>
                    <th>HSN Code</th>
                    <th>Quantity</th>
                    <th>Rate</th>
                    <th>Amount</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td></td>
                    <td>Selective Pallet Racking System</td>
                    <td>94032010</td>
                    <td>22.00 NOS</td>
                    <td>20,600.00</td>
                    <td>4,53,200.00</td>
                </tr>
            </table>

            <table style="border: 1px solid #000;">
                <tr>
                    <td class="no-border"><strong>Exemption Notification No:</strong></td>
                    <td class="no-border"></td>
                </tr>
                <tr>
                    <td class="no-border"><strong>Payment Terms:</strong></td>
                    <td class="no-border">50% Advance 50% at the Time of Delivery</td>
                </tr>
                <tr>
                    <td class="no-border"><strong>Remarks:</strong></td>
                    <td class="no-border"></td>
                </tr>
            </table>
{{--
            <table>

            </table> --}}

            <table>
                <tr>
                    <td colspan="6"><strong>Mode of Transport:</strong></td>
                    <td colspan="6"><strong>Vehicle No:</strong> TN24AE6518</td>
                    <td colspan="2"><strong>Value Of Goods</strong></td>
                    <td colspan="2"><strong>4,53,200.00</strong></td>
                </tr>
                {{-- <tr>
                    <td class="bold">Value Of Goods</td>
                    <td class="right">4,53,200.00</td>
                </tr> --}}
                <tr>
                    <td colspan="12" style=" border-bottom:none !important;" ><strong>Total Amount (in Words):</strong><br>
                        INR Five Lakh Thirty Four Thousand Seven Hundred Seventy Six Only
                    </td>
                    {{-- <td colspan="4"></td> --}}
                    <td colspan="2">CGST@9%</td>
                    <td colspan="2" class="right">40,788.00</td>
                </tr>
                <tr>
                    <td colspan="12" class="rno-border"></td>
                    {{-- <td colspan="2"></td> --}}
                    <td colspan="2">SGST@9%</td>
                    <td colspan="2" class="right">40,788.00</td>
                </tr>
                <tr>
                    <td colspan="12" class="rno-border"></td>
                    {{-- <td colspan="2"></td> --}}
                    <td colspan="2" class="bold">Total Amount</td>
                    <td colspan="2" class="right bold">5,34,776.00</td>
                </tr>
                <tr>
                    <td colspan="12" class="rno-border"></td>
                    {{-- <td colspan="2"></td> --}}
                    <td colspan="2" class="bold">Advance Amount</td>
                    <td colspan="2" class="right bold"></td>
                </tr>
                <tr>
                    <td colspan="12" style=" border-top:none !important;"><strong>Total Tax Paid (Both in words & figures):</strong><br>
                        INR Eighty One Thousand Five Hundred Seventy Six
                    </td>
                    {{-- <td colspan="2"></td> --}}
                    <td colspan="2" class="bold">Balance Amount</td>
                    <td colspan="2" class="right bold">5,34,776.00</td>
                </tr>
            </table>

            <table>
                <tr>
                    <td >Certified that the particulars given above are true and correct.<br>
                        TERMS AND SALES<br>
                        Goods once sold will not be taken back or exchanged.Seller is not responsible for any loss or damage of goods in transit.Buyer
                        undertakes to submit required Declaration to the seller on demand.Dispute if any will be to Chennai Jurisdiction only EOE<br>

                        Company Account Details<br>

                        Bank Name: ICICI BANK LTD - Account Number: 737005500005 - Account Holder name: MERCURI INDUSTRIAL
                        SOLUTIONS - Ifsc Code: ICIC0007370

                    </td>
                </tr>

            </table>
        </div>


    </div>
</body>
</html>

